projects:
  famdoc:
    schemaPath: src/_lib/graphql/schema.json
    includes:
      - src/_lib/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/_lib/graphql
extensions:
  amplify:
    version: 3
